// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7G8n9jwdE5WowDWbWsVZ26
// Component: YwX3tQC_9DPMnH
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_full_commerce_storefront_primary_copy.module.css"; // plasmic-import: 7G8n9jwdE5WowDWbWsVZ26/projectcss
import sty from "./PlasmicRating.module.css"; // plasmic-import: YwX3tQC_9DPMnH/css

import EmptyStarIcon from "./icons/PlasmicIcon__EmptyStar"; // plasmic-import: xkJ1kda2MK1XqW/icon
import FullStarIcon from "./icons/PlasmicIcon__FullStar"; // plasmic-import: 8LIhzzrak_Njjm/icon
import HalfStarIcon from "./icons/PlasmicIcon__HalfStar"; // plasmic-import: fwMWvYlz7uozBv/icon

export type PlasmicRating__VariantMembers = {
  rating:
    | "one"
    | "two"
    | "three"
    | "four"
    | "five"
    | "half"
    | "oneHalf"
    | "twoHalf"
    | "threeHalf"
    | "fourHalf";
};

export type PlasmicRating__VariantsArgs = {
  rating?: SingleChoiceArg<
    | "one"
    | "two"
    | "three"
    | "four"
    | "five"
    | "half"
    | "oneHalf"
    | "twoHalf"
    | "threeHalf"
    | "fourHalf"
  >;
};

type VariantPropType = keyof PlasmicRating__VariantsArgs;
export const PlasmicRating__VariantProps = new Array<VariantPropType>("rating");

export type PlasmicRating__ArgsType = {};
type ArgPropType = keyof PlasmicRating__ArgsType;
export const PlasmicRating__ArgProps = new Array<ArgPropType>();

export type PlasmicRating__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultRatingProps {
  rating?: SingleChoiceArg<
    | "one"
    | "two"
    | "three"
    | "four"
    | "five"
    | "half"
    | "oneHalf"
    | "twoHalf"
    | "threeHalf"
    | "fourHalf"
  >;
  className?: string;
}

function PlasmicRating__RenderFunc(props: {
  variants: PlasmicRating__VariantsArgs;
  args: PlasmicRating__ArgsType;
  overrides: PlasmicRating__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "half")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "one")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__jMmis, {
          [sty.svgrating_five__jMmiscGQlM]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svgrating_fourHalf__jMmis4OXac]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svgrating_four__jMmispe7VX]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svgrating_half__jMmisBYmvS]: hasVariant(
            variants,
            "rating",
            "half"
          ),
          [sty.svgrating_oneHalf__jMmisTpVp]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),
          [sty.svgrating_one__jMmis0RvKo]: hasVariant(
            variants,
            "rating",
            "one"
          ),
          [sty.svgrating_threeHalf__jMmisy1BHx]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),
          [sty.svgrating_three__jMmisCwieb]: hasVariant(
            variants,
            "rating",
            "three"
          ),
          [sty.svgrating_twoHalf__jMmisz7Jx]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),
          [sty.svgrating_two__jMmisZFa8C]: hasVariant(variants, "rating", "two")
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__rHTc, {
          [sty.svgrating_five__rHTccGQlM]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svgrating_fourHalf__rHTc4OXac]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svgrating_four__rHTcpe7VX]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svgrating_oneHalf__rHTcTpVp]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),
          [sty.svgrating_threeHalf__rHTcy1BHx]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),
          [sty.svgrating_three__rHTcCwieb]: hasVariant(
            variants,
            "rating",
            "three"
          ),
          [sty.svgrating_twoHalf__rHTcz7Jx]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),
          [sty.svgrating_two__rHTcZFa8C]: hasVariant(variants, "rating", "two")
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__aXdUv, {
          [sty.svgrating_five__aXdUVcGQlM]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svgrating_fourHalf__aXdUv4OXac]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svgrating_four__aXdUVpe7VX]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svgrating_threeHalf__aXdUVy1BHx]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),
          [sty.svgrating_three__aXdUvcwieb]: hasVariant(
            variants,
            "rating",
            "three"
          ),
          [sty.svgrating_twoHalf__aXdUVz7Jx]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg___9Z5Dl, {
          [sty.svgrating_five___9Z5DlcGQlM]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svgrating_fourHalf___9Z5Dl4OXac]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svgrating_four___9Z5Dlpe7VX]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svgrating_threeHalf___9Z5Dly1BHx]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? HalfStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__k7WD, {
          [sty.svgrating_five__k7WDcGQlM]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svgrating_fourHalf__k7WD4OXac]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          )
        })}
        role={"img"}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRating__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRating__VariantsArgs;
    args?: PlasmicRating__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRating__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRating__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRating__ArgProps,
      internalVariantPropNames: PlasmicRating__VariantProps
    });

    return PlasmicRating__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRating";
  } else {
    func.displayName = `PlasmicRating.${nodeName}`;
  }
  return func;
}

export const PlasmicRating = Object.assign(
  // Top-level PlasmicRating renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicRating
    internalVariantProps: PlasmicRating__VariantProps,
    internalArgProps: PlasmicRating__ArgProps
  }
);

export default PlasmicRating;
/* prettier-ignore-end */
